apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zync-que-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - replicationcontrollers
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - get
      - list
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - delete
      - patch
      - update