apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zync-que-rolebinding
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: zync
    threescale_component_element: que
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zync-que-role
subjects:
  - kind: ServiceAccount
    name: zync-que-sa