apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zync-que-role
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: zync
    threescale_component_element: que
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - replicationcontrollers
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - replicasets
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - delete
      - patch
      - update