apiVersion: v1
kind: ServiceAccount
metadata:
  name: zync-que-sa
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: zync
    threescale_component_element: que