apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-worker
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: backend
    threescale_component_element: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      threescale_component: backend
      threescale_component_element: worker
  strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
  progressDeadlineSeconds: 1200
  template:
    metadata:
    {{- with .Values.backendWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "3scale-amp-chart.selectorLabels" . | nindent 8 }}
        threescale_component: backend
        threescale_component_element: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "3scale-amp-chart.serviceAccountName" . }}
      containers:
        - name: backend-worker
          args:
            - bin/3scale_backend_worker
            - run
          env:
            - name: CONFIG_REDIS_PROXY
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_URL
                  name: backend-redis
            - name: CONFIG_REDIS_SENTINEL_HOSTS
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_SENTINEL_HOSTS
                  name: backend-redis
            - name: CONFIG_REDIS_SENTINEL_ROLE
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_SENTINEL_ROLE
                  name: backend-redis
            - name: CONFIG_QUEUES_MASTER_NAME
              valueFrom:
                secretKeyRef:
                  key: REDIS_QUEUES_URL
                  name: backend-redis
            - name: CONFIG_QUEUES_SENTINEL_HOSTS
              valueFrom:
                secretKeyRef:
                  key: REDIS_QUEUES_SENTINEL_HOSTS
                  name: backend-redis
            - name: CONFIG_QUEUES_SENTINEL_ROLE
              valueFrom:
                secretKeyRef:
                  key: REDIS_QUEUES_SENTINEL_ROLE
                  name: backend-redis
            - name: RACK_ENV
              valueFrom:
                configMapKeyRef:
                  key: RACK_ENV
                  name: backend-environment
            - name: CONFIG_EVENTS_HOOK
              valueFrom:
                secretKeyRef:
                  key: url
                  name: system-events-hook
            - name: CONFIG_EVENTS_HOOK_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  key: password
                  name: system-events-hook
          image: {{ .Values.backendWorker.image }}
          imagePullPolicy: {{ .Values.backendWorker.imagePullPolicy }}
          resources:
            {{- toYaml .Values.backendWorker.resources | nindent 12 }}
      initContainers:
        - name: backend-redis-svc
          command:
            - /opt/app/entrypoint.sh
            - sh
            - -c
            - until rake connectivity:redis_storage_queue_check; do sleep $SLEEP_SECONDS;
              done
          env:
            - name: CONFIG_REDIS_PROXY
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_URL
                  name: backend-redis
            - name: CONFIG_REDIS_SENTINEL_HOSTS
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_SENTINEL_HOSTS
                  name: backend-redis
            - name: CONFIG_REDIS_SENTINEL_ROLE
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_SENTINEL_ROLE
                  name: backend-redis
            - name: CONFIG_QUEUES_MASTER_NAME
              valueFrom:
                secretKeyRef:
                  key: REDIS_QUEUES_URL
                  name: backend-redis
            - name: CONFIG_QUEUES_SENTINEL_HOSTS
              valueFrom:
                secretKeyRef:
                  key: REDIS_QUEUES_SENTINEL_HOSTS
                  name: backend-redis
            - name: CONFIG_QUEUES_SENTINEL_ROLE
              valueFrom:
                secretKeyRef:
                  key: REDIS_QUEUES_SENTINEL_ROLE
                  name: backend-redis
            - name: RACK_ENV
              valueFrom:
                configMapKeyRef:
                  key: RACK_ENV
                  name: backend-environment
            - name: SLEEP_SECONDS
              value: "1"
          image: {{ .Values.backendWorker.image }}
          resources: {}  
      {{- with .Values.backendWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}