apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cron
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: backend
    threescale_component_element: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      threescale_component: backend
      threescale_component_element: cron
  strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
  progressDeadlineSeconds: 1200
  template:
    metadata:
    {{- with .Values.backendCron.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "3scale-amp-chart.selectorLabels" . | nindent 8 }}
        threescale_component: backend
        threescale_component_element: cron
    spec:
      containers:
        - name: backend-cron
          args:
            - backend-cron
          env:
            {{- include "3scale-amp-chart.backendRedisEnvironment" . | nindent 12 }}
            - name: RACK_ENV
              valueFrom:
                configMapKeyRef:
                  key: RACK_ENV
                  name: backend-environment
          image: {{ .Values.backendCron.image }}
          imagePullPolicy: {{ .Values.backendCron.imagePullPolicy }}
          resources:
            {{- toYaml .Values.backendCron.resources | nindent 12 }}
      initContainers:
        - name: backend-redis-svc
          command:
            - /opt/app/entrypoint.sh
            - sh
            - -c
            - until rake connectivity:redis_storage_queue_check; do sleep $SLEEP_SECONDS;
              done
          env:
            {{- include "3scale-amp-chart.backendRedisEnvironment" . | nindent 12 }}
            - name: RACK_ENV
              valueFrom:
                configMapKeyRef:
                  key: RACK_ENV
                  name: backend-environment
            - name: SLEEP_SECONDS
              value: "1"
          image: {{ .Values.backendCron.image }}
          resources: {}  
      serviceAccountName: {{ include "3scale-amp-chart.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendCron.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendCron.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendCron.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}