apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-redis
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: backend
    threescale_component_element: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      threescale_component: backend
      threescale_component_element: redis
  strategy:
    type: Recreate
  template:
    metadata:
    {{- with .Values.backendRedis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "3scale-amp-chart.selectorLabels" . | nindent 8 }}
        threescale_component: backend
        threescale_component_element: redis
    spec:
      volumes:
        - name: backend-redis-storage
          persistentVolumeClaim:
            claimName: backend-redis-storage
        - configMap:
            items:
              - key: redis.conf
                path: redis.conf
            name: backend-redis-config
          name: backend-redis-config
      containers:
        - name: backend-redis
          args:
            - /etc/redis.d/redis.conf
            - --daemonize
            - "no"
          command:
            - /opt/rh/rh-redis32/root/usr/bin/redis-server
          image: {{ .Values.backendRedis.image }}
          imagePullPolicy: {{ .Values.backendRedis.imagePullPolicy }}
          resources:
            {{- toYaml .Values.backendRedis.resources | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 6379
          readinessProbe:
            exec:
              command:
                - container-entrypoint
                - bash
                - -c
                - redis-cli set liveness-probe "`date`" | grep OK
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: backend-redis-storage
            - mountPath: /etc/redis.d/
              name: backend-redis-config
      serviceAccountName: {{ include "3scale-amp-chart.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendRedis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendRedis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendRedis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}