apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-sphinx
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: sphinx
spec:
  replicas: 1
  selector:
    matchLabels:
      threescale_component: system
      threescale_component_element: sphinx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  progressDeadlineSeconds: 1200
  template:
    metadata:
    {{- with .Values.systemSphinx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "3scale-amp-chart.selectorLabels" . | nindent 8 }}
        threescale_component: system
        threescale_component_element: sphinx
    spec:
      volumes:
        - emptyDir: {}
          name: system-sphinx-database
      initContainers:
        - name: check-system-master-svc
          command:
            - sh
            - -c
            - until $(curl --output /dev/null --silent --fail --head http://system-master:3000/status);
              do sleep $SLEEP_SECONDS; done
          env:
            - name: SLEEP_SECONDS
              value: "1"
          image: {{ .Values.systemSphinx.image }}
          imagePullPolicy: {{ .Values.systemSphinx.imagePullPolicy }}
      containers:
        - name: system-sphinx
          args:
            - rake
            - openshift:thinking_sphinx:start
          env:
            {{- include "3scale-amp-chart.systemRedisEnvironment" . | nindent 12 }}
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  key: RAILS_ENV
                  name: system-environment
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: system-database
            - name: THINKING_SPHINX_ADDRESS
              value: 0.0.0.0
            - name: THINKING_SPHINX_CONFIGURATION_FILE
              value: db/sphinx/production.conf
            - name: THINKING_SPHINX_PID_FILE
              value: db/sphinx/searchd.pid
            - name: DELTA_INDEX_INTERVAL
              value: "5"
            - name: FULL_REINDEX_INTERVAL
              value: "60"
          image: {{ .Values.systemSphinx.image }}
          imagePullPolicy: {{ .Values.systemSphinx.imagePullPolicy }}
          resources:
            {{- toYaml .Values.systemSphinx.resources | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            tcpSocket:
              port: 9306
          volumeMounts:
            - mountPath: /opt/system/db/sphinx
              name: system-sphinx-database
      serviceAccountName: {{ include "3scale-amp-chart.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.systemSphinx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.systemSphinx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.systemSphinx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}