apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-app
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: app
spec:
  replicas: 1
  selector:
    matchLabels:
      threescale_component: system
      threescale_component_element: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  progressDeadlineSeconds: 1200
  template:
    metadata:
    {{- with .Values.systemApp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "3scale-amp-chart.selectorLabels" . | nindent 8 }}
        threescale_component: system
        threescale_component_element: app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "3scale-amp-chart.serviceAccountName" . }}
      volumes:
        - name: system-storage
          persistentVolumeClaim:
            claimName: system-storage
        - name: system-config 
          configMap:
            name: system-config 
            items:
              - key: zync.yml
                path: zync.yml
              - key: rolling_updates.yml
                path: rolling_updates.yml
              - key: service_discovery.yml
                path: service_discovery.yml          
      initContainers:
        - name: deploy
          command:
            - bash
            - -c
            - bundle exec rake boot openshift:deploy
          env:
            {{- include "3scale-amp-chart.systemEnvironment" . | nindent 12 }}
            {{- include "3scale-amp-chart.systemRedisEnvironment" . | nindent 12 }}
          image: {{ .Values.systemApp.image }}
          imagePullPolicy: {{ .Values.systemApp.imagePullPolicy }}
          resources:
            {{- toYaml .Values.systemApp.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/system/public/system
              name: system-storage
            - mountPath: /opt/system-extra-configs
              name: system-config
        - name: post-deploy
          command:
            - bash
            - -c
            - bundle exec rake boot openshift:post_deploy
          env:
            {{- include "3scale-amp-chart.systemEnvironment" . | nindent 12 }}
          image: {{ .Values.systemApp.image }}
          imagePullPolicy: {{ .Values.systemApp.imagePullPolicy }}
          resources:
            {{- toYaml .Values.systemApp.resources | nindent 12 }}
      containers:
        - name: system-master
          args:
            - env
            - TENANT_MODE=master
            - PORT=3002
            - container-entrypoint
            - bundle
            - exec
            - unicorn
            - -c
            - config/unicorn.rb
          env:
            {{- include "3scale-amp-chart.systemEnvironment" . | nindent 12 }}
            {{- include "3scale-amp-chart.systemRedisEnvironment" . | nindent 12 }}
          image: {{ .Values.systemApp.image }}
          imagePullPolicy: {{ .Values.systemApp.imagePullPolicy }}
          resources:
            {{- toYaml .Values.systemApp.resources | nindent 12 }}
          ports:
            - name: master
              containerPort: 3002
              protocol: TCP
          livenessProbe:
            failureThreshold: 40
            initialDelaySeconds: 40
            periodSeconds: 10
            tcpSocket:
              port: master
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              httpHeaders:
              - name: X-Forwarded-Proto
                value: https
              path: /check.txt
              port: master
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /opt/system/public/system
              name: system-storage
            - mountPath: /opt/system-extra-configs
              name: system-config
      {{- with .Values.systemApp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.systemApp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.systemApp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}