apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-storage
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: {{ .Values.storageClassRWX }}