apiVersion: v1
kind: Service
metadata:
  name: apicast-staging
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: apicast
    threescale_component_element: staging
spec:
  ports:
    - name: gateway
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: management
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    {{- include "3scale-amp-chart.selectorLabels" . | nindent 4 }}
    threescale_component: apicast
    threescale_component_element: staging