apiVersion: v1
kind: Service
metadata:
  name: system-memcache
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: memcache
spec:
  ports:
    - name: memcache
      port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    {{- include "3scale-amp-chart.selectorLabels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: memcache