apiVersion: v1
kind: Service
metadata:
  name: system-sphinx
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: sphinx
spec:
  ports:
    - name: sphinx
      port: 9306
      protocol: TCP
      targetPort: 9306
  selector:
    {{- include "3scale-amp-chart.selectorLabels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: sphinx