apiVersion: v1
kind: Service
metadata:
  name: system-mysql
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: mysql
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    {{- include "3scale-amp-chart.selectorLabels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: mysql