apiVersion: v1
kind: Service
metadata:
  name: system-provider
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: provider
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: provider
  selector:
    {{- include "3scale-amp-chart.selectorLabels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: app