apiVersion: v1
kind: Service
metadata:
  name: system-developer
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: developer
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: developer
  selector:
    {{- include "3scale-amp-chart.selectorLabels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: app