apiVersion: v1
kind: Service
metadata:
  name: zync
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: zync
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "3scale-amp-chart.selectorLabels" . | nindent 4 }}
    threescale_component: zync