apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: mysql
  name: system-mysql-config
data:
  my.cnf: |
    !include /etc/my.cnf
    !includedir /etc/my-extra.d
