apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
    threescale_component_element: mysql
  name: system-mysql-extra-config
data:
  mysql-charset.cnf: |
    [client]
    default-character-set = utf8
    [mysql]
    default-character-set = utf8
    [mysqld]
    character-set-server = utf8
    collation-server = utf8_unicode_ci