apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: zync
  name: zync-config
data:
  integrations.yml: |
    shared: &shared
      kubernetes: 1

    production:
      <<: *shared

    development:
      <<: *shared

    test:
      <<: *shared
