apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: backend
  name: backend-listener
type: Opaque
stringData:
  {{- include "3scale-amp-chart.mergeSecretsFromValues" . -}}
  {{- toYaml .Values.secrets.backendListener | nindent 2 }}