apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: backend
  name: backend-listener
type: Opaque
stringData:
  route_endpoint: https://backend-{{ .Values.tenantName }}.{{ .Values.wildcardDomain }}
  service_endpoint: http://backend-listener:3000