{{/* Re-use an existing password if it is already set to avoid regenerating */}}
{{- $systemBackendPassword := default (randAlphaNum 8) .Values.systemBackendPassword }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "backend-internal-api") }}
{{- if $secret }}
{{- $systemBackendPassword = index $secret.data "password" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: backend
  name: backend-internal-api
type: Opaque
stringData:
  username: {{ default "3scale_api_user" .Values.systemBackendUsername }}
  password: {{ $systemBackendPassword }}