{{/* Re-use an existing shared secret if it is already set to avoid regenerating */}}
{{- $systemBackendSecret := default (randAlphaNum 8) .Values.systemBackendSecret | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "system-events-hook") }}
{{- if $secret }}
{{- $systemBackendSecret = index $secret.data "password" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
  name: system-events-hook
type: Opaque
stringData:
  url: http://system-master:3000/master/events/import
  password: {{ $systemBackendSecret }}