apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
  name: system-events-hook
type: Opaque
stringData:
  {{- include "3scale-amp-chart.mergeSecretsFromValues" . -}}
  {{- toYaml .Values.secrets.systemEventsHook | nindent 2 }}