apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: system
  name: system-redis
type: Opaque
stringData:
  {{- include "3scale-amp-chart.mergeSecretsFromValues" (merge (dict "name" "systemRedis") .) | nindent 2 }}