apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: zync
  name: zync
type: Opaque
stringData:
  {{- include "3scale-amp-chart.mergeSecretsFromValues" (merge (dict "name" "zync") .) | nindent 2 }}