apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: backend
spec:
  tls:
    - hosts:
        - backend-{{ .Values.tenantName }}.{{ .Values.wildcardDomain }}
      secretName: backend-tls
  rules:
    - host: backend-{{ .Values.tenantName }}.{{ .Values.wildcardDomain }}
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-listener
                port:
                  name: http