apiVersion: v1
kind: Service
metadata:
  name: backend-redis
  labels:
    {{- include "3scale-amp-chart.labels" . | nindent 4 }}
    threescale_component: backend
    threescale_component_element: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "3scale-amp-chart.selectorLabels" . | nindent 4 }}
    threescale_component: backend
    threescale_component_element: redis